Gather updated lists of files, samples, metadata\
KL 2 April 2026\
Getting ready to setup a database, just with sample information

In [2]:
import pandas as pd
import os

import pdb

In [3]:
#data will be in test_data, that's already behind .gitignore

In [57]:
#start with the sequence data, Luis gave me three lists. 
#Merge these and pull out relevant details, export to CSV file that will be read into the database
seqDir = '../test_data/Luis_fileLists'

dir_list = os.listdir(seqDir)
dir_list_full = [os.path.join(seqDir,f) for f in os.listdir(seqDir)]

In [58]:
#will be hard enough as is, let's start with the files in Cyverse only
df = pd.read_csv(os.path.join(seqDir,'files_shortList.txt'),sep='\t',header=None,comment = '#')

In [59]:
df.loc[0].to_string()

'0    /iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz'

In [60]:
df.head()

                                                                                                                                 0
0    /iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz
1    /iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R2_001.fastq.gz
2  /iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R1_001.fastq.gz
3  /iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R2_001.fastq.gz
4    /iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s003-index--CTCTAGAG-TACGAGAC-148-0_S3_R1_001.fastq.gz

In [68]:
#also, strip off the fastq.gz (not working yet)
#.str.rstrip('fastq.gz')

for index,row in df.iterrows():
    file = os.path.basename(row.to_string())
    df.loc[index,'filename'] = file

df.head()

,0,filename
0,/iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz,lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz\nfilename lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz
1,/iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R2_001.fastq.gz,lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R2_001.fastq.gz\nfilename lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R2_001.fastq.gz
2,/iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R1_001.fastq.gz,lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R1_001.fastq.gz\nfilename lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R1_001.fastq.gz
3,/iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R2_001.fastq.gz,lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R2_001.fastq.gz\nfilename lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R2_001.fastq.gz
4,/iplant/home/btemperton/BIOS-SCOPE/data/sequencing/1001_amplicon/lane1-s003-index--CTCTAGAG-TACGAGAC-148-0_S3_R1_001.fastq.gz,lane1-s003-index--CTCTAGAG-TACGAGAC-148-0_S3_R1_001.fastq.gz\nfilename lane1-s003-index--CTCTAGAG-TACGAGAC-148-0_S3_R1_001.fastq.gz

In [72]:
## now, where is the information on what these samples are?
#files for each sequencing it seems, found them on Google Drive. Bring them in here and start linking them.
#for now, start with the file that I know has the information I need:
data_dir = '../test_data/BIOS-SCOPE time series/'
fName = 'V4_dada2_read_info_03052026.csv'
df_info = pd.DataFrame(pd.read_csv(os.path.join(data_dir,fName)))

In [73]:
df_info.head()

,Unnamed: 0,Reads In,Filter/Trim Reads,Merged Reads,Non-chimeric (Final) Reads,Sequence Run
0,lane1-s001-indexN716-D-S518-D-ACTCGCTA-CTATTAAG-BSv4-342_S1_L001_R1_001.fastq,120327,114368,104773,102336,210105_M01498_0751_000000000-JFLB7
1,lane1-s002-indexN716-D-S520-D-ACTCGCTA-AAGGCTAT-BSv4-343_S2_L001_R1_001.fastq,37466,34983,30837,30327,210105_M01498_0751_000000000-JFLB7
2,lane1-s003-indexN716-D-S521-D-ACTCGCTA-GAGCCTTA-BSv4-344_S3_L001_R1_001.fastq,98948,93754,84934,83129,210105_M01498_0751_000000000-JFLB7
3,lane1-s004-indexN716-D-S522-D-ACTCGCTA-TTATGCGA-BSv4-345_S4_L001_R1_001.fastq,76783,71629,62949,61409,210105_M01498_0751_000000000-JFLB7
4,lane1-s005-indexN716-D-S513-D-ACTCGCTA-TCGACTAG-BSv4-346_S5_L001_R1_001.fastq,60554,56847,49914,48997,210105_M01498_0751_000000000-JFLB7